(()=>{'use strict';
const storeKey='xlerobot-field-guide-v1';let state={checks:{},entries:[]};let storageOK=true;
try{const saved=JSON.parse(localStorage.getItem(storeKey)||'null');if(saved&&typeof saved==='object')state={checks:saved.checks||{},entries:Array.isArray(saved.entries)?saved.entries:[],start:saved.start||''}}catch{storageOK=false}
const status=document.querySelector('#save-status');const save=()=>{try{localStorage.setItem(storeKey,JSON.stringify(state));if(status)status.textContent='Saved in this browser only. Export before switching devices.'}catch{storageOK=false;if(status)status.textContent='Browser storage is unavailable. Export your notes before leaving this page.'}};
if(!storageOK&&status)status.textContent='Browser storage is unavailable. Export your notes before leaving this page.';
document.querySelectorAll('[data-check]').forEach(el=>{el.checked=!!state.checks[el.dataset.check];el.addEventListener('change',()=>{state.checks[el.dataset.check]=el.checked;save()})});
const start=document.querySelector('#trial-start');if(start){start.value=state.start||new Date().toLocaleDateString('en-CA');start.addEventListener('change',()=>{state.start=start.value;save()})}
const entries=document.querySelector('#journal-entries');const renderEntries=()=>{if(!entries)return;entries.replaceChildren();if(!state.entries.length){const p=document.createElement('p');p.className='empty';p.textContent='No observations yet. Start with your leak test or first sowing.';entries.append(p);return}for(const e of [...state.entries].reverse()){const box=document.createElement('article');box.className='journal-entry';const h=document.createElement('strong');h.textContent=`${e.date} · ${e.kit} · ${e.stage}`;const p=document.createElement('p');p.textContent=`Paper: ${e.moisture}. Water added: ${e.water===''?'not measured':e.water+' mL'}.\n${e.notes}`;box.append(h,p);entries.append(box)}};renderEntries();
const form=document.querySelector('#journal-form');if(form)form.addEventListener('submit',ev=>{ev.preventDefault();const d=new FormData(form);state.entries.push({date:new Date().toLocaleString(),kit:d.get('kit'),stage:d.get('stage'),moisture:d.get('moisture'),water:d.get('water'),notes:d.get('notes')});state.start=start.value;save();renderEntries();form.reset()});
const exp=document.querySelector('#export-notes');if(exp)exp.addEventListener('click',()=>{const blob=new Blob([JSON.stringify({format:'xlerobot-ny-trial-v1',exported:new Date().toISOString(),...state},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='xlerobot-ny-trial-notes.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
const q=document.querySelector('#site-search'),results=document.querySelector('#search-results');let index=[];if(q){fetch('data/search.json').then(r=>r.json()).then(data=>{index=data;if(q.value)search()}).catch(()=>{results.textContent='Search unavailable; use the navigation links.'});function search(){const words=q.value.toLowerCase().trim().split(/\s+/).filter(Boolean);results.replaceChildren();if(!words.length)return;const matches=index.filter(x=>words.every(w=>(x.title+' '+x.text).toLowerCase().includes(w))).slice(0,8);if(!matches.length){results.textContent='No matching topic. Try “wick”, “wiring”, “cart” or “recovery”.';return}for(const item of matches){const a=document.createElement('a');a.href=item.url;a.textContent=item.title;results.append(a)}}q.addEventListener('input',search)}
})();
