"""One source for the HTML software-roadmap presentation and its speaker notes."""
from html import escape
SLIDES = [
('overview','The software we are building','Roadmap · Sep 22–Oct 10','assets/assembly-v3.png','Blender layout of robot, table and growing trays',
 'One supervised care cycle: inspect a tray, measure light, get a human watering decision, pour and record the outcome.',
 'Build software on the Mac before travel; connect the real robot from September 30.',
 'Two arms, existing cameras, a bottle and paper-growing trays. One optional light paddle.',
 'A cycle can explain what happened, pause when uncertain and recover without repeating a pour.',
 'These are proposed deliverables, not completed robot software. The NY print/growing trial is physical work already in scope; September 30 remains the start of robot commissioning. The Blender hardware and interfaces are illustrations. Actual planter meshes are used, but robot/table shapes do not validate reach or load capacity.'),
('hardware','The hardware defines the software','Scope · first supervised build','assets/blender/roadmap-hardware.png','Mac at upper left, USB hub at center, camera and motor interfaces at left, ESP32 at right, light board below',
 'The Mac coordinates the work. Each device gets a small adapter that reports its identity, status and errors.',
 'Create a named configuration for motor ports, camera views, tray positions and enabled sensors.',
 'Hub carries USB data. Motor supplies are separate. ESP32 connects the optional light sensor.',
 'Disabled devices are recorded as not applicable; an absent probe never becomes a “dry” reading.',
 'The paper-tray profile defers moisture probe, relay, pump, scale and pod-moving operations. The first build uses head/wrist cameras, not a fixed overhead camera. Human checks of water reserve and paper wetness remain required. The assembly guide identifies the recorded two-wheel kit; do not use a three-wheel motor map. <a href="assembly.html#connections">Connection checklist</a>.'),
('schedule','A simulator before the robot arrives','Sep 22–24 · build and interrupt','assets/blender/roadmap-simulator.png','Blender planter models representing simulated tray responses',
 'Practice the entire sequence with virtual devices, including failures between steps.',
 'Build explicit states, transition deadlines and fake camera, arm and light responses.',
 'Virtual versions stand in for the tray, cameras, gripper, bottle and ESP32. They move no hardware.',
 'Interrupt every state. Restart into a known state or a review request, never a blind watering retry.',
 'Sequence: identify, inspect, measure, request human refill authorization, supervised care, verify, park. Each transition lists its required evidence and timeout. Pick/dock/weigh/return states from the redline apply only to a future pod-handling profile; mark them not applicable here. Keep simulated and physical episodes distinguishable in every saved record. Dates are targets; a failed test holds the previous operating level.'),
('evidence','A durable record of every action','Sep 22–24 · save before acting','assets/blender/roadmap-record.png','Blender concept of reviewing photographs and action records on the Mac',
 '“We sent the pour command” and “water reached the tray” are different facts.',
 'Save intended, attempted and verified stages with cycle IDs, command IDs and original evidence.',
 'Camera images, light readings, motor feedback and human water checks meet in the Mac’s local journal.',
 'After a crash, a possibly completed pour remains UNKNOWN until someone reconciles the outcome.',
 'Use SQLite plus image files as the proposed local store. Save intent before dispatch and an attempted record before a possible physical effect. Duplicate IDs return existing records; IDs cannot guarantee exactly-once physical watering. Include tray/recipe, timestamps, units, validity, calibration IDs, software/model versions, interventions and outcome evidence. Distinguish estimated, measured, human-attested, unknown and not-attempted delivery. A visible wetness change is not a measured volume.'),
('light-adapter','Readable light measurements','Sep 25–26 · validate the sensor adapter','assets/blender/usb-link.png','ESP32 linked to the powered hub by a USB data cable',
 'A light number needs a time, a known pose and a validity flag before it is useful.',
 'Build ESP32 serial parsing, freshness checks and a record of light level, spread and errors.',
 'One BH1750 sends readings through the ESP32 and USB hub to the Mac.',
 'A disconnected cable, old sample or sensor error produces INVALID—not a fabricated value.',
 'First test with short bench wires. Firmware pin choices must match the delivered ESP32 and BH1750. At the actual configured conversion timing, collect distinct fresh readings after motion settles; roughly ten over two seconds is a starting procedure, not an accuracy guarantee. Log pose, height, median/spread, saturation and bus errors. Lux is not PPFD. Optional air sensing stays on the robot body. <a href="assembly.html#step-9">Light circuit assembly</a>.'),
('cycle','A camera record for the correct tray','Sep 25–26 · identify and inspect','assets/blender/care-inspect.png','Robot camera observing the planted cress tray',
 'The software must know which tray it sees and whether that view is fresh and usable.',
 'Build tray identity checks, image timestamps and a visible record of crop and refill area.',
 'Use the robot’s existing head and wrist cameras while the base stays parked.',
 'A wrong tray, covered refill opening or stale image blocks the relevant care action.',
 'Store original images rather than only a model summary. A camera index can change after reconnecting: map views to names and verify them. A planned camera view is not proof that a waterline is visible. For this paper-tray profile, a person checks both the water reserve and a seed-free paper edge and authorizes each refill. Removing the soil probe does not validate camera-only wetness estimation.'),
('gates','Fault tests for unclear views','Sep 25–26 · make failures reproducible','assets/blender/roadmap-occlusion.png','Camera with an illustrative obstruction blocking the crop view',
 'A blocked camera means “unknown,” even if a classifier says the scene looks normal.',
 'Build replay cases for stale images, occlusion, glare, wrong identity, cable loss and interrupted actions.',
 'Head/wrist camera coverage includes the refill target and the area where a spill could appear.',
 'Spill status has three outcomes: CLEAR, SPILL or UNKNOWN. An unseen area cannot pass as clear.',
 'Dedicated leak pads are deferred. Camera spill detection is experimental: evaluate tiny clear-water spills, shadows, glare and arm occlusion, plus false clearances and recovery latency. Include uncertain grip, dropped acknowledgements and cloud loss. Probe-contact/scale faults are conditional tests only if those optional profiles are enabled. Relevant local stop behavior must survive cloud loss.'),
('review','An exception viewer for a person','Sep 22–26 · review without a terminal','assets/blender/roadmap-review.png','Blender laptop concept showing paused status and unknown delivery',
 'When the robot pauses, show the evidence and the reason—not just an error code.',
 'Build a viewer with the latest image, its age, current action, last verified state and eligible next steps.',
 'It runs on the Mac using camera and action records; remote access is a later secured integration.',
 'For unknown delivery, “retry watering” is unavailable. A person can request inspection and reconcile.',
 'Example: the Mac loses the motor acknowledgement during a pour. Persist UNKNOWN delivery. The viewer offers reinspection or caretaker service, not a second dose. Record reviewer identity, time, physical findings and resolution. A confirmation button must correspond to an actual inspection. A remote viewer is not itself a safety mechanism or permission to expose robot controls publicly.'),
('models','Jev and Astra review the evidence','Sep 25–26 · shadow mode first','assets/blender/roadmap-models.png','Blender concept of comparing rules, Jev and Astra on one computer',
 'Jev classifies incidents. Astra investigates them and proposes experiments or changes.',
 'Build a shadow adapter and compare their suggestions with rules using the same saved episodes.',
 'They consume camera, sensor and action records. The local controller retains physical permission checks.',
 'Neither model can override stale evidence, uncertain grip or a missing human refill authorization.',
 'Jev categories: normal, needs reinspection, handling fault, watering discrepancy, crop concern and unknown. Allow abstention. The feedback’s 0.85 heuristic is not a validated threshold; the described helper source has not been audited here. Track missed faults, false clearances, unnecessary alerts, review time, latency and cost. The suggested 120 labeled episodes and ten per priority fault class are initial collection targets, not proof of reliability. Astra proposes versioned changes; automatic code modification/retraining remains deferred.'),
('preflight','A rehearsal before travel','Sep 27–29 · freeze and restore','assets/blender/dry-packing.png','Clean dry growing parts and electronics arranged for travel',
 'Arrive with a rehearsed software package and a recorded growing recipe.',
 'Freeze configuration, export an incident bundle, restore a backup and rehearse offline recovery.',
 'Carry the software and clean dry parts; preserve NY growing observations separately.',
 'A fresh environment can recover the saved records and resolve a defined simulated exception.',
 'Version code, model, recipe and calibration files. Store original evidence with its identifiers and keep a working rollback. Arrange local care or end the NY growing trial before departure. Seeds and live growth remain subject to the separate travel plan. The packing render does not establish airline clearance. <a href="japan.html">Travel plan</a> · <a href="growing.html#journal">Trial notebook</a>.'),
('commission','Connect the real hardware','Sep 30–Oct 2 · days 1–3','assets/blender/light-tool.png','One light board fitted to the actual printed paddle mesh',
 'Replace simulated device responses with measured behavior from the assembled robot.',
 'Connect motor/camera/ESP32 adapters, save arm calibration and commission light-reading poses.',
 'Fit the light paddle, dry electronics enclosure and moving cable; verify the two-wheel robot configuration.',
 'Readings remain valid throughout the cable sweep, and empty-arm stops and camera views work together.',
 'Use supplied wall power first after label checks. Verify bottle/tool fits and real reach; a Blender view is not a fit test. Keep base driving disabled during the first farm routine. The light face points upward at canopy height, outside arm/cable shadow. Repeatability alone is not absolute calibration. Existing motor leads do not replace the additional sensor harness. <a href="assembly.html#computer">Robot commissioning steps</a>.'),
('watering','A small supervised bottle pour','Sep 30–Oct 2 · days 1–3','assets/blender/care-water.png','Illustrative gripper tipping a small bottle toward a refill opening',
 'Turn a tested pickup, approach and upright return into one bounded care operation.',
 'Build supervised motion steps with grip/target checks, action records and state-specific recovery.',
 'Gripper holds a small bottle; the tray stays still. Its built-in water supply is refilled by pouring.',
 'Test delivery into a kitchen measure across fill levels. A tilt duration is never labeled measured volume.',
 'The selected wide-mouth bottle needs a tested outlet or a suitable household replacement. First rehearse empty. Then test small fills over household containment with a person present. Require known fill, correct tray, fresh view, clear reachable target and human-confirmed need before a pour. While control exists, use the commissioned upright-return action; do not blindly release or de-energize a tilted bottle. Total power loss may leave it draining. No pump or relay actuates watering.'),
('complete-cycle','A complete parked care cycle','Oct 3–5 · days 4–6','assets/blender/care-park.png','Bottle upright and light paddle returned to its rest beside the tray',
 'Join inspection, optional light measurement, human review, watering and verification into one routine.',
 'Build the cycle runner across every intended tray position, with deadlines and persistent recovery.',
 'One tool at a time in the gripper. Trays stay located; bottle and paddle return to known rests.',
 'Every outcome and intervention is saved. Unknown delivery pauses the cycle without repeating water.',
 'Human checks water reserve and paper wetness: a full trough can coexist with dry paper if its wick disconnects. Light measurement does not decide thirst. Capture task demonstrations only once teleoperation and the full supervised sequence are reliable. If a future workflow moves pods, reintroduce pick/dock/return states and independent grip/location evidence. A motion-complete message alone cannot close an uncertain physical action.'),
('evaluate','Evaluate against real observations','Oct 3–8 · collect, label and compare','assets/blender/growth-stages.png','Illustrative growth stages in repeated small cress trays',
 'Use repeatable crop observations and independently labeled incidents to judge changes.',
 'Build dataset exports, held-out comparisons and a regression set of actual failures and recoveries.',
 'Use the same crop lot and record tray, light, water checks and interventions; kit geometry still differs.',
 'A candidate change improves the chosen measures on held-out episodes before a bounded supervised trial.',
 'Growth illustrations are not predictions. Keep simulated episodes separate from real ones and do not tune on the evaluation set. Re-run relevant physical tests after changes to motion, wiring or watering. No ready-to-run autonomous plant-watering checkpoint was established; the upstream bottle demo is teleoperated. Training a task policy requires our own reliable demonstrations and real-world evaluation. Keep recipes fixed within comparisons or record necessary deviations.'),
('observation','Longer observation windows','Oct 6–8 · days 7–9','assets/blender/care-measure.png','Robot holding one light paddle over the crop',
 'Extend monitoring only after the relevant fault tests pass.',
 'Freeze features, evaluate alerts and rehearse 2-hour, then 8-hour, then 24-hour observation windows.',
 'The parked robot observes the crop and takes validated readings; a person remains assigned to watering.',
 'Each window produces reviewable records and alerts. Longer monitoring does not grant autonomous pouring.',
 'A failed gate keeps the previous operating level. Expand water-control authority only under a separately validated delivery and recovery profile. Navigation, automatic refill, printer pickup and construction tasks remain deferred. Human response availability is part of the observation plan; passing an offline replay does not demonstrate unattended hardware reliability.'),
('handoff','A caretaker can take over','Oct 9–10 · days 10–11','assets/germination-exploded-v3.png','Exploded Blender view of the square tray, insert and cover',
 'Finish with an understandable system and a repeatable way to inspect and refill the trays.',
 'Repeat weak cases, restore backups, export the dataset and write the caretaker’s recovery instructions.',
 'The caretaker can identify each tray, inspect paper/water, refill manually and park the tools.',
 'Another person resolves representative exceptions and restores the saved configuration successfully.',
 'Deliver code/configuration versions, calibration records, camera/tray identities, incident bundles and operating limits. Keep hardware assembly and the combined growing guide linked below. Plans are not measured performance: record which gates actually passed and unresolved cases. The modular table is still subject to actual geometry, stiffness and reach checks; a household surface is sufficient for growing tests. <a href="assembly.html">Assembly guide</a> · <a href="growing.html">Growing and kit instructions</a>.')
]

def render():
    out='''<link rel="stylesheet" href="roadmap.css"><script src="roadmap.js" defer></script><div class="roadmap" id="roadmap"><div class="roadmap-toolbar" aria-label="Slideshow controls"><a href="index.html">Field guide</a><label for="slide-jump" class="sr-only">Choose roadmap slide</label><select id="slide-jump">'''
    for n,s in enumerate(SLIDES,1):out+=f'<option value="{s[0]}">{n:02} · {escape(s[1])}</option>'
    out+='''</select><button type="button" id="slide-prev">Previous</button><button type="button" id="slide-next">Next</button><button type="button" id="read-all" aria-pressed="false">Read all</button><button type="button" id="present" aria-pressed="false">Present</button></div><p class="roadmap-disclosure">Proposed software · Blender illustrations · Human-supervised watering</p><div class="roadmap-slides">'''
    for n,(key,title,when,img,alt,lead,build,hardware,proof,notes) in enumerate(SLIDES,1):
        out+=f'''<section id="{key}" class="roadmap-slide" aria-labelledby="title-{key}" data-slide><div class="slide-heading"><p class="roadmap-date">{escape(when)} · {n:02} / {len(SLIDES):02}</p><h2 id="title-{key}" tabindex="-1">{escape(title)}</h2></div><div class="slide-composition"><figure><a href="{img}" target="_blank" rel="noopener" aria-label="Open illustration: {escape(alt,quote=True)}"><img src="{img}" alt="{escape(alt,quote=True)}" {'loading="eager"' if n==1 else 'loading="lazy"'} width="1440" height="1000"></a><figcaption>{escape(alt)}. Illustration, not a commissioned system.</figcaption></figure><div class="slide-copy"><p class="slide-lead">{escape(lead)}</p><dl><dt>Build</dt><dd>{escape(build)}</dd><dt>Hardware</dt><dd>{escape(hardware)}</dd><dt>Ready when</dt><dd>{escape(proof)}</dd></dl></div></div><details class="slide-notes"><summary>Implementation notes and limits</summary><p>{notes}</p></details></section>'''
    out+='''</div><div class="roadmap-bottom"><output id="slide-position" aria-live="polite" aria-atomic="true">1 / 16</output></div><p class="roadmap-help">Use Left / Right arrow keys. Read all shows the full roadmap and loads its illustrations for browser Print. Printing includes every slide and its notes.</p><details class="roadmap-sources"><summary>Sources and editable Blender files</summary><p>Based on the supplied redline PowerPoint and September 20 software-roadmap feedback, updated for the paper-tray, bottle-watering and September 30 commissioning decisions. This presentation documents proposed work; it does not implement robot controls.</p><p><a href="downloads/software-roadmap-scenes.blend">Six additional roadmap Blender scenes</a> · <a href="downloads/farm-visual-atlas.blend">Original 17-scene visual atlas</a> · <a href="downloads/MODEL-CREDITS.md">Model credits</a></p><p><a href="https://xlerobot.readthedocs.io/en/latest/software/">Upstream XLeRobot software</a> · <a href="https://vector-wangel.github.io/XLeRobot-assets/videos/Real_demos/xlerobot030.mp4#t=56,60">Teleoperated bottle demo</a> · <a href="https://xlerobot.readthedocs.io/en/latest/software/getting_started/VLA_ACT.html">Task-training workflow</a> · <a href="https://www.mouser.com/datasheet/2/348/bh1750fvi-e-186247.pdf">Light-sensor timing reference</a></p></details></div>'''
    return out
